In [1]:
setwd("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/pseudobulk_test/yao_2021/ACA_MOp_VISp")

library(dplyr)

source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/code/enrichment_fxns.R")
source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/code/gene_mapping_fxns.R")
source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/code/top_corr_module_fxns.R")

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Loading required package: future


Attaching package: ‘reshape2’


The following object is masked from ‘package:tidyr’:

    smiths



Attaching package: ‘data.table’


The following objects are masked from ‘package:reshape2’:

    dcast, melt


The following objects are masked from ‘package:dplyr’:

    between, first, last

Here I perform enrichment analysis to find modules enriched for cell type markers. 

These modules will later be used to correlate with exon PSI to define cell type-specific exons.

In [2]:
mod_def <- "PosBC"
strict <- FALSE
lfc_threshold <- 3
pval_threshold <- 0.05

## Prep DE genes

### Pseudobulk DE genes

In [3]:
pairwise_res_list <- readRDS("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/pseudobulk_test/yao_2021/ACA_MOp_VISp/data/DE_genes/yao_2021_ACA_MOp_VISp_STAR_donor_subclass_label_pseudobulk_pairwise_DE_genes_dream.RDS")

ctypes <- unique(sapply(strsplit(names(pairwise_res_list), "_vs_"), "[", 1))
n_signif_wrt <- length(ctypes)-2
if (strict) {
    n_signif_wrt <- NULL
}

marker_genes_list <- prep_pairwise_DE_genes(pairwise_res_list, pval_threshold=pval_threshold, lfc_threshold=lfc_threshold, strict=strict, n_signif_wrt=n_signif_wrt)
marker_genes_list <- marker_genes_list[lengths(marker_genes_list) > 2]

set_source <- paste0("yao_2021_ACA_MOp_VISp_STAR_donor_subclass_label_pseudobulk_pairwise_DE_genes_strict", strict, "_logFC", lfc_threshold, "_nSignif", n_signif_wrt)

### Claude marker genes

In [3]:
set_source <- "Claude_marker_genes"

marker_genes_list <- readRDS("/mnt/lareaulab/reliscu/projects/NSF_GRFP/data/marker_genes/AI/Claude_cortical_markers_mouse.RDS")

names(marker_genes_list) <- sapply(names(marker_genes_list), function(x) gsub(" ", "_", gsub("/", "_", x, fixed=TRUE)))
names(marker_genes_list)

 [1] "All_Neuronal"      "All_Glutamatergic" "All_GABAergic"
 [4] "CGE_Class"         "MGE_Class"         "L2_3_IT"
 [7] "L4_IT"             "L5_IT"             "L5_ET"
[10] "L5_6_NP"           "L6_CT"             "L6_IT"
[13] "L6_IT_Car3"        "L6b"               "Lamp5"
[16] "Lamp5_Lhx6"        "Sncg"              "Vip"
[19] "Pax6"              "Pvalb"             "Chandelier"
[22] "Sst"               "Sst_Chodl"         "Astro"
[25] "Oligo"             "OPC"               "Micro_PVM"
[28] "Endo"              "VLMC"              "Peri"

## Get enrichments

### 20pcntCells_25SD_200samples_mergeParam0.97_subsetCutoff851.92_Modules

In [33]:
network_dir <- "yao_2021_ACA_MOp_VISp_STAR_SyntheticDataset1_20pcntCells_25SD_200samples_mergeParam0.97_subsetCutoff851.92_Modules"

In [35]:
enrichments_df <- get_module_enrichments(network_dir, marker_genes_list, mod_def)

In [37]:
# Get most enriched cell type for each module
# If cell type is most enriched in multiple modules, choose module with smallest p-value

top_mods_df <- enrichments_df %>%
    group_by(Cell_type) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    group_by(Network, Module) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    arrange(Qval)
    
top_mods_df[,c("Cell_type", "Pval", "Qval", "Module", "Network")]

   Cell_type   Pval          Qval          Module
1  Astro        0.000000e+00  0.000000e+00 blue
2  Micro-PVM    0.000000e+00  0.000000e+00 brown
3  Endo         0.000000e+00  0.000000e+00 turquoise
4  SMC-Peri    4.145293e-231 4.402441e-228 brown
5  Oligo       5.613860e-208 5.585554e-205 green
6  VLMC        1.115298e-168 8.858747e-166 red
7  Sst         1.133229e-146 8.434172e-144 black
8  Sst_Chodl    1.061343e-77  5.364665e-75 cyan
9  Car3         1.193794e-67  5.613859e-65 palevioletred3
10 Lamp5        3.476726e-37  1.095412e-34 navajowhite4
11 Sncg         8.949755e-37  2.801125e-34 magenta4
12 L5_6_NP_CTX  6.198227e-34  1.786167e-31 skyblue4
13 Meis2        2.113215e-30  5.326486e-28 cyan
14 L6b_CTX      1.853116e-26  4.121374e-24 lightpink
15 Vip          4.036424e-26  8.893399e-24 tan2
16 Pvalb        4.732251e-25  1.023563e-22 cornsilk2
17 L2_3_IT_CTX  3.288896e-22  6.572298e-20 darkgoldenrod4
18 L6_CT_CTX    2.155657e-21  4.132959e-19 azure
19 L5_PT_CTX    2.919051e-20  5.295809e-18 seashell4
20 L4_5_IT_CTX  6.919984e-15  9.910360e-13 rosybrown3
21 L6_IT_CTX    1.140344e-03  6.241252e-02 dodgerblue3
   Network
1  Bicor-None_signum0.257_minSize10_merge_ME_0.97_20250
2  Bicor-None_signum0.257_minSize10_merge_ME_0.97_20250
3  Bicor-None_signum0.257_minSize10_merge_ME_0.97_20250
4  Bicor-None_signum0.971_minSize10_merge_ME_0.97_20250
5  Bicor-None_signum0.92_minSize6_merge_ME_0.97_20250
6  Bicor-None_signum0.92_minSize6_merge_ME_0.97_20250
7  Bicor-None_signum0.971_minSize3_merge_ME_0.97_20250
8  Bicor-None_signum0.741_minSize3_merge_ME_0.97_20250
9  Bicor-None_signum0.343_minSize10_merge_ME_0.97_20250
10 Bicor-None_signum0.741_minSize3_merge_ME_0.97_20250
11 Bicor-None_signum0.741_minSize4_merge_ME_0.97_20250
12 Bicor-None_signum0.343_minSize8_merge_ME_0.97_20250
13 Bicor-None_signum0.291_minSize6_merge_ME_0.97_20250
14 Bicor-None_signum0.435_minSize6_merge_ME_0.97_20250
15 Bicor-None_signum0.291_minSize8_merge_ME_0.97_20250
16 Bicor-None_signum0.435_minSize4_merge_ME_0.97_20250
17 Bicor-None_signum0.257_minSize8_merge_ME_0.97_20250
18 Bicor-None_signum0.435_minSize4_merge_ME_0.97_20250
19 Bicor-None_signum0.291_minSize4_merge_ME_0.97_20250
20 Bicor-None_signum0.257_minSize6_merge_ME_0.97_20250
21 Bicor-None_signum0.291_minSize4_merge_ME_0.97_20250

In [38]:
write.csv(top_mods_df, file=paste0("data/enrichments/", network_dir, "_", set_source, "_enrichments.csv"), row.names=FALSE, quote=FALSE)

### 10pcntCells_5SD_200samples_mergeParam0.95_subsetCutoff763.45_Modules

In [15]:
network_dir <- "yao_2021_ACA_MOp_VISp_STAR_SyntheticDataset1_10pcntCells_5SD_200samples_mergeParam0.95_subsetCutoff763.45_Modules"

In [26]:
enrichments_df <- get_module_enrichments(network_dir, marker_genes_list, mod_def)

In [27]:
# Get most enriched cell type for each module
# If cell type is most enriched in multiple modules, choose module with smallest p-value

top_mods_df <- enrichments_df %>%
    group_by(Cell_type) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    group_by(Network, Module) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    arrange(Qval)

top_mods_df[,c("Cell_type", "Pval", "Qval", "Module", "Network")]

   Cell_type   Pval          Qval          Module
1  Endo         0.000000e+00  0.000000e+00 turquoise
2  Micro-PVM    0.000000e+00  0.000000e+00 turquoise
3  SMC-Peri    1.457365e-230 3.087047e-227 brown
4  VLMC        5.442796e-206 1.086195e-202 yellow
5  Oligo       1.608078e-197 2.934100e-194 green
6  Astro       6.738938e-189 1.195431e-185 lightcyan
7  Sst_Chodl    8.636439e-64  2.626341e-61 orangered4
8  Sst          1.084343e-61  3.091393e-59 floralwhite
9  Car3         1.012593e-60  2.717026e-58 maroon
10 Meis2        1.546021e-36  2.828952e-34 darkslateblue
11 Lamp5        1.045655e-15  8.774846e-14 darkgoldenrod3
12 L6b_CTX      1.154193e-15  9.672953e-14 orange4
13 L5_6_NP_CTX  2.530774e-13  1.963764e-11 red4
14 L6_CT_CTX    9.145255e-13  6.878977e-11 dodgerblue1
15 Sncg         2.651738e-10  1.801517e-08 coral3
16 Vip          3.563286e-10  2.405444e-08 dodgerblue4
17 Pvalb        4.209783e-10  2.829905e-08 darkolivegreen2
18 L6_IT_CTX    3.259010e-04  1.369234e-02 chocolate1
19 L4_5_IT_CTX  1.628642e-03  6.224473e-02 darksalmon
20 L2_3_IT_CTX  1.628708e-03  6.224473e-02 peachpuff3
21 L5_PT_CTX    1.000000e+00  1.000000e+00 antiquewhite4
   Network
1  Bicor-None_signum0.135_minSize10_merge_ME_0.95_18409
2  Bicor-None_signum0.742_minSize10_merge_ME_0.95_18409
3  Bicor-None_signum0.742_minSize10_merge_ME_0.95_18409
4  Bicor-None_signum0.742_minSize8_merge_ME_0.95_18409
5  Bicor-None_signum0.423_minSize10_merge_ME_0.95_18409
6  Bicor-None_signum0.742_minSize4_merge_ME_0.95_18409
7  Bicor-None_signum0.423_minSize6_merge_ME_0.95_18409
8  Bicor-None_signum0.742_minSize3_merge_ME_0.95_18409
9  Bicor-None_signum0.175_minSize8_merge_ME_0.95_18409
10 Bicor-None_signum0.742_minSize3_merge_ME_0.95_18409
11 Bicor-None_signum0.423_minSize3_merge_ME_0.95_18409
12 Bicor-None_signum0.423_minSize3_merge_ME_0.95_18409
13 Bicor-None_signum0.209_minSize4_merge_ME_0.95_18409
14 Bicor-None_signum0.135_minSize6_merge_ME_0.95_18409
15 Bicor-None_signum0.135_minSize6_merge_ME_0.95_18409
16 Bicor-None_signum0.135_minSize6_merge_ME_0.95_18409
17 Bicor-None_signum0.209_minSize6_merge_ME_0.95_18409
18 Bicor-None_signum0.135_minSize6_merge_ME_0.95_18409
19 Bicor-None_signum0.135_minSize6_merge_ME_0.95_18409
20 Bicor-None_signum0.209_minSize4_merge_ME_0.95_18409
21 Bicor-None_signum0.135_minSize10_merge_ME_0.95_18409

In [28]:
write.csv(top_mods_df, file=paste0("data/enrichments/", network_dir, "_", set_source, "_enrichments.csv"), row.names=FALSE, quote=FALSE)

### 10pcntCells_20SD_200samples_mergeParam0.95_subsetCutoff825.95_Modules

##### Fisher method

In [4]:
network_dir <- "yao_2021_ACA_MOp_VISp_STAR_SyntheticDataset1_10pcntCells_20SD_200samples_mergeParam0.95_subsetCutoff825.95_Modules"

In [5]:
enrichments_df <- get_module_enrichments(network_dir, marker_genes_list, mod_def)

In [6]:
# Get most enriched cell type for each module
# If cell type is most enriched in multiple modules, choose module with smallest p-value

top_mods_df <- enrichments_df %>%
    group_by(Cell_type) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    group_by(Network, Module) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    arrange(Qval)

top_mods_df[,c("Cell_type", "Pval", "Qval", "Module", "Network")]

   Cell_type         Pval         Qval         Module
1  Oligo             1.757007e-29 1.123940e-24 red
2  Micro_PVM         2.246532e-29 1.123940e-24 turquoise
3  Astro             2.922182e-24 9.867549e-21 brown
4  Endo              3.637903e-22 9.254455e-19 blue
5  VLMC              3.230714e-18 4.998947e-15 green
6  All_GABAergic     8.212922e-16 1.022962e-12 orangered1
7  OPC               1.770810e-14 1.983440e-11 paleturquoise
8  Peri              3.134024e-13 3.384069e-10 yellow
9  Pvalb             6.404358e-13 6.769226e-10 chocolate3
10 Sst_Chodl         2.921672e-12 2.923425e-09 lightyellow
11 L6b               8.011891e-12 7.758095e-09 cyan1
12 All_Glutamatergic 6.648557e-11 5.065390e-08 darkviolet
13 L5_ET             1.083163e-10 7.778565e-08 tomato2
14 All_Neuronal      2.342667e-08 1.311981e-05 saddlebrown
15 Vip               2.370340e-08 1.322544e-05 royalblue3
16 L5_6_NP           2.651740e-08 1.474073e-05 lavenderblush3
17 Sncg              6.288343e-08 3.221220e-05 skyblue4
18 Lamp5             8.728903e-08 4.284517e-05 magenta4
19 Sst               2.479391e-07 1.134548e-04 tan1
20 MGE_Class         3.404564e-06 1.468365e-03 firebrick3
21 L4_IT             6.098592e-06 2.622744e-03 darkgoldenrod3
22 Lamp5_Lhx6        8.361861e-06 3.575589e-03 blueviolet
23 L6_IT_Car3        1.809656e-05 7.110244e-03 plum2
24 CGE_Class         2.651135e-05 9.752669e-03 darkolivegreen4
25 L2_3_IT           4.032804e-05 1.339123e-02 thistle4
26 Pax6              9.774905e-04 2.648223e-01 deepskyblue1
27 L5_IT             1.086012e-03 2.910746e-01 ivory2
28 Chandelier        1.357368e-03 3.476575e-01 violetred3
29 L6_CT             1.493023e-03 3.734798e-01 bisque2
30 L6_IT             1.845719e-03 4.418245e-01 seashell3
   Network
1  Bicor-None_signum0.438_minSize4_merge_ME_0.95_18409
2  Bicor-None_signum0.438_minSize4_merge_ME_0.95_18409
3  Bicor-None_signum0.724_minSize8_merge_ME_0.95_18409
4  Bicor-None_signum0.438_minSize4_merge_ME_0.95_18409
5  Bicor-None_signum0.438_minSize4_merge_ME_0.95_18409
6  Bicor-None_signum0.438_minSize8_merge_ME_0.95_18409
7  Bicor-None_signum0.9_minSize3_merge_ME_0.95_18409
8  Bicor-None_signum0.35_minSize10_merge_ME_0.95_18409
9  Bicor-None_signum0.438_minSize6_merge_ME_0.95_18409
10 Bicor-None_signum0.724_minSize3_merge_ME_0.95_18409
11 Bicor-None_signum0.35_minSize4_merge_ME_0.95_18409
12 Bicor-None_signum0.724_minSize4_merge_ME_0.95_18409
13 Bicor-None_signum0.35_minSize4_merge_ME_0.95_18409
14 Bicor-None_signum0.9_minSize3_merge_ME_0.95_18409
15 Bicor-None_signum0.24_minSize6_merge_ME_0.95_18409
16 Bicor-None_signum0.3_minSize4_merge_ME_0.95_18409
17 Bicor-None_signum0.724_minSize3_merge_ME_0.95_18409
18 Bicor-None_signum0.24_minSize6_merge_ME_0.95_18409
19 Bicor-None_signum0.438_minSize6_merge_ME_0.95_18409
20 Bicor-None_signum0.438_minSize4_merge_ME_0.95_18409
21 Bicor-None_signum0.35_minSize6_merge_ME_0.95_18409
22 Bicor-None_signum0.24_minSize8_merge_ME_0.95_18409
23 Bicor-None_signum0.3_minSize4_merge_ME_0.95_18409
24 Bicor-None_signum0.724_minSize4_merge_ME_0.95_18409
25 Bicor-None_signum0.3_minSize8_merge_ME_0.95_18409
26 Bicor-None_signum0.3_minSize4_merge_ME_0.95_18409
27 Bicor-None_signum0.3_minSize4_merge_ME_0.95_18409
28 Bicor-None_signum0.3_minSize4_merge_ME_0.95_18409
29 Bicor-None_signum0.3_minSize4_merge_ME_0.95_18409
30 Bicor-None_signum0.3_minSize4_merge_ME_0.95_18409

In [8]:
write.csv(top_mods_df, file=paste0("data/enrichments/", network_dir, "_", set_source, "_enrichments.csv"), row.names=FALSE, quote=FALSE)

In [7]:
set_source

[1] "Claude_marker_genes"

##### fgsea

In [ ]:
network_dir <- "yao_2021_ACA_MOp_VISp_STAR_SyntheticDataset1_10pcntCells_20SD_200samples_mergeParam0.95_subsetCutoff825.95_Modules"

enrichments_df <- get_module_enrichments_fgsea_par(network_dir, marker_genes_list, n_workers=20)

In [ ]:
# Get most enriched cell type for each module
# If cell type is most enriched in multiple modules, choose module with smallest p-value

top_mods_df <- enrichments_df %>%
    group_by(Cell_type) %>%
    slice_min(Padj, with_ties=FALSE) %>%
    group_by(Network, Module) %>%
    arrange(Network) %>%
    slice_min(Padj, with_ties=FALSE) %>%
    arrange(Padj)

In [ ]:
write.csv(top_mods_df, file=paste0("data/enrichments/", network_dir, "_", set_source, "_fgsea.csv"), row.names=FALSE)