In [12]:
setwd("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/pseudobulk_test/yao_2021/ACA_MOp_VISp")

library(dplyr)

source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/code/enrichment_fxns.R")
source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/code/gene_mapping_fxns.R")
source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/code/top_corr_module_fxns.R")

Here I perform enrichment analysis to find modules enriched for cell type markers. 

These modules will later be used to correlate with exon PSI to define cell type-specific exons.

In [24]:
mod_def <- "PosBC"
strict <- FALSE
lfc_threshold <- 3
pval_threshold <- 0.05

## Prep DE genes

### Pseudobulk DE genes

In [25]:
pairwise_res_list <- readRDS("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/pseudobulk_test/yao_2021/ACA_MOp_VISp/data/DE_genes/yao_2021_ACA_MOp_VISp_STAR_donor_subclass_label_pseudobulk_pairwise_DE_genes_dream.RDS")

ctypes <- unique(sapply(strsplit(names(pairwise_res_list), "_vs_"), "[", 1))
n_signif_wrt <- length(ctypes)-2
if (strict) {
    n_signif_wrt <- NULL
}

marker_genes_list <- prep_pairwise_DE_genes(pairwise_res_list, pval_threshold=pval_threshold, lfc_threshold=lfc_threshold, strict=strict, n_signif_wrt=n_signif_wrt)
marker_genes_list <- marker_genes_list[lengths(marker_genes_list) > 2]

set_source <- paste0("yao_2021_ACA_MOp_VISp_STAR_donor_subclass_label_pseudobulk_pairwise_DE_genes_strict", strict, "_logFC", lfc_threshold, "_nSignif", n_signif_wrt)

### Claude marker genes

In [ ]:
set_source <- "Claude_marker_genes"

marker_genes_list <- readRDS("/mnt/lareaulab/reliscu/projects/NSF_GRFP/data/marker_genes/AI/Claude_cortical_markers_mouse.RDS")

names(marker_genes_list) <- sapply(names(marker_genes_list), function(x) gsub(" ", "_", gsub("/", "_", x, fixed=TRUE)))
names(marker_genes_list)

## Get enrichments

### 20pcntCells_25SD_200samples_mergeParam0.97_subsetCutoff851.92_Modules

In [33]:
network_dir <- "yao_2021_ACA_MOp_VISp_STAR_SyntheticDataset1_20pcntCells_25SD_200samples_mergeParam0.97_subsetCutoff851.92_Modules"

In [35]:
enrichments_df <- get_module_enrichments(network_dir, marker_genes_list, mod_def)

In [37]:
# Get most enriched cell type for each module
# If cell type is most enriched in multiple modules, choose module with smallest p-value

top_mods_df <- enrichments_df %>%
    group_by(Cell_type) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    group_by(Network, Module) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    arrange(Qval)
    
top_mods_df[,c("Cell_type", "Pval", "Qval", "Module", "Network")]

   Cell_type   Pval          Qval          Module
1  Astro        0.000000e+00  0.000000e+00 blue
2  Micro-PVM    0.000000e+00  0.000000e+00 brown
3  Endo         0.000000e+00  0.000000e+00 turquoise
4  SMC-Peri    4.145293e-231 4.402441e-228 brown
5  Oligo       5.613860e-208 5.585554e-205 green
6  VLMC        1.115298e-168 8.858747e-166 red
7  Sst         1.133229e-146 8.434172e-144 black
8  Sst_Chodl    1.061343e-77  5.364665e-75 cyan
9  Car3         1.193794e-67  5.613859e-65 palevioletred3
10 Lamp5        3.476726e-37  1.095412e-34 navajowhite4
11 Sncg         8.949755e-37  2.801125e-34 magenta4
12 L5_6_NP_CTX  6.198227e-34  1.786167e-31 skyblue4
13 Meis2        2.113215e-30  5.326486e-28 cyan
14 L6b_CTX      1.853116e-26  4.121374e-24 lightpink
15 Vip          4.036424e-26  8.893399e-24 tan2
16 Pvalb        4.732251e-25  1.023563e-22 cornsilk2
17 L2_3_IT_CTX  3.288896e-22  6.572298e-20 darkgoldenrod4
18 L6_CT_CTX    2.155657e-21  4.132959e-19 azure
19 L5_PT_CTX    2.919051e-20  5.295809e-18 seashell4
20 L4_5_IT_CTX  6.919984e-15  9.910360e-13 rosybrown3
21 L6_IT_CTX    1.140344e-03  6.241252e-02 dodgerblue3
   Network
1  Bicor-None_signum0.257_minSize10_merge_ME_0.97_20250
2  Bicor-None_signum0.257_minSize10_merge_ME_0.97_20250
3  Bicor-None_signum0.257_minSize10_merge_ME_0.97_20250
4  Bicor-None_signum0.971_minSize10_merge_ME_0.97_20250
5  Bicor-None_signum0.92_minSize6_merge_ME_0.97_20250
6  Bicor-None_signum0.92_minSize6_merge_ME_0.97_20250
7  Bicor-None_signum0.971_minSize3_merge_ME_0.97_20250
8  Bicor-None_signum0.741_minSize3_merge_ME_0.97_20250
9  Bicor-None_signum0.343_minSize10_merge_ME_0.97_20250
10 Bicor-None_signum0.741_minSize3_merge_ME_0.97_20250
11 Bicor-None_signum0.741_minSize4_merge_ME_0.97_20250
12 Bicor-None_signum0.343_minSize8_merge_ME_0.97_20250
13 Bicor-None_signum0.291_minSize6_merge_ME_0.97_20250
14 Bicor-None_signum0.435_minSize6_merge_ME_0.97_20250
15 Bicor-None_signum0.291_minSize8_merge_ME_0.97_20250
16 Bicor-None_signum0.435_minSize4_merge_ME_0.97_20250
17 Bicor-None_signum0.257_minSize8_merge_ME_0.97_20250
18 Bicor-None_signum0.435_minSize4_merge_ME_0.97_20250
19 Bicor-None_signum0.291_minSize4_merge_ME_0.97_20250
20 Bicor-None_signum0.257_minSize6_merge_ME_0.97_20250
21 Bicor-None_signum0.291_minSize4_merge_ME_0.97_20250

In [38]:
write.csv(top_mods_df, file=paste0("data/enrichments/", network_dir, "_", set_source, "_enrichments.csv"), row.names=FALSE, quote=FALSE)

### 10pcntCells_5SD_200samples_mergeParam0.95_subsetCutoff763.45_Modules

In [15]:
network_dir <- "yao_2021_ACA_MOp_VISp_STAR_SyntheticDataset1_10pcntCells_5SD_200samples_mergeParam0.95_subsetCutoff763.45_Modules"

In [26]:
enrichments_df <- get_module_enrichments(network_dir, marker_genes_list, mod_def)

In [27]:
# Get most enriched cell type for each module
# If cell type is most enriched in multiple modules, choose module with smallest p-value

top_mods_df <- enrichments_df %>%
    group_by(Cell_type) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    group_by(Network, Module) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    arrange(Qval)

top_mods_df[,c("Cell_type", "Pval", "Qval", "Module", "Network")]

   Cell_type   Pval          Qval          Module
1  Endo         0.000000e+00  0.000000e+00 turquoise
2  Micro-PVM    0.000000e+00  0.000000e+00 turquoise
3  SMC-Peri    1.457365e-230 3.087047e-227 brown
4  VLMC        5.442796e-206 1.086195e-202 yellow
5  Oligo       1.608078e-197 2.934100e-194 green
6  Astro       6.738938e-189 1.195431e-185 lightcyan
7  Sst_Chodl    8.636439e-64  2.626341e-61 orangered4
8  Sst          1.084343e-61  3.091393e-59 floralwhite
9  Car3         1.012593e-60  2.717026e-58 maroon
10 Meis2        1.546021e-36  2.828952e-34 darkslateblue
11 Lamp5        1.045655e-15  8.774846e-14 darkgoldenrod3
12 L6b_CTX      1.154193e-15  9.672953e-14 orange4
13 L5_6_NP_CTX  2.530774e-13  1.963764e-11 red4
14 L6_CT_CTX    9.145255e-13  6.878977e-11 dodgerblue1
15 Sncg         2.651738e-10  1.801517e-08 coral3
16 Vip          3.563286e-10  2.405444e-08 dodgerblue4
17 Pvalb        4.209783e-10  2.829905e-08 darkolivegreen2
18 L6_IT_CTX    3.259010e-04  1.369234e-02 chocolate1
19 L4_5_IT_CTX  1.628642e-03  6.224473e-02 darksalmon
20 L2_3_IT_CTX  1.628708e-03  6.224473e-02 peachpuff3
21 L5_PT_CTX    1.000000e+00  1.000000e+00 antiquewhite4
   Network
1  Bicor-None_signum0.135_minSize10_merge_ME_0.95_18409
2  Bicor-None_signum0.742_minSize10_merge_ME_0.95_18409
3  Bicor-None_signum0.742_minSize10_merge_ME_0.95_18409
4  Bicor-None_signum0.742_minSize8_merge_ME_0.95_18409
5  Bicor-None_signum0.423_minSize10_merge_ME_0.95_18409
6  Bicor-None_signum0.742_minSize4_merge_ME_0.95_18409
7  Bicor-None_signum0.423_minSize6_merge_ME_0.95_18409
8  Bicor-None_signum0.742_minSize3_merge_ME_0.95_18409
9  Bicor-None_signum0.175_minSize8_merge_ME_0.95_18409
10 Bicor-None_signum0.742_minSize3_merge_ME_0.95_18409
11 Bicor-None_signum0.423_minSize3_merge_ME_0.95_18409
12 Bicor-None_signum0.423_minSize3_merge_ME_0.95_18409
13 Bicor-None_signum0.209_minSize4_merge_ME_0.95_18409
14 Bicor-None_signum0.135_minSize6_merge_ME_0.95_18409
15 Bicor-None_signum0.135_minSize6_merge_ME_0.95_18409
16 Bicor-None_signum0.135_minSize6_merge_ME_0.95_18409
17 Bicor-None_signum0.209_minSize6_merge_ME_0.95_18409
18 Bicor-None_signum0.135_minSize6_merge_ME_0.95_18409
19 Bicor-None_signum0.135_minSize6_merge_ME_0.95_18409
20 Bicor-None_signum0.209_minSize4_merge_ME_0.95_18409
21 Bicor-None_signum0.135_minSize10_merge_ME_0.95_18409

In [28]:
write.csv(top_mods_df, file=paste0("data/enrichments/", network_dir, "_", set_source, "_enrichments.csv"), row.names=FALSE, quote=FALSE)

### 10pcntCells_20SD_200samples_mergeParam0.95_subsetCutoff825.95_Modules

In [29]:
network_dir <- "yao_2021_ACA_MOp_VISp_STAR_SyntheticDataset1_10pcntCells_20SD_200samples_mergeParam0.95_subsetCutoff825.95_Modules"

In [30]:
enrichments_df <- get_module_enrichments(network_dir, marker_genes_list, mod_def)

In [31]:
# Get most enriched cell type for each module
# If cell type is most enriched in multiple modules, choose module with smallest p-value

top_mods_df <- enrichments_df %>%
    group_by(Cell_type) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    group_by(Network, Module) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    arrange(Qval)

top_mods_df[,c("Cell_type", "Pval", "Qval", "Module", "Network")]

   Cell_type   Pval          Qval          Module
1  Endo         0.000000e+00  0.000000e+00 brown
2  Astro        0.000000e+00  0.000000e+00 brown
3  Micro-PVM    0.000000e+00  0.000000e+00 turquoise
4  Oligo       3.100470e-220 3.832290e-217 red
5  SMC-Peri    1.497465e-184 1.498364e-181 yellow
6  VLMC        2.915599e-166 2.735014e-163 red
7  Sst         3.747688e-145 3.005674e-142 grey60
8  Sst_Chodl    6.302657e-78  3.699308e-75 ivory
9  Car3         2.027528e-65  1.034069e-62 antiquewhite4
10 Lamp5        6.070678e-41  2.327751e-38 mediumorchid
11 Meis2        6.291123e-33  1.922500e-30 grey60
12 L5_6_NP_CTX  9.661313e-33  2.916800e-30 brown2
13 Sncg         7.372842e-32  2.151702e-29 antiquewhite2
14 L6b_CTX      2.375265e-28  5.684567e-26 orangered1
15 Vip          4.585109e-28  1.080101e-25 pink4
16 L6_CT_CTX    2.904979e-27  6.411886e-25 seashell3
17 Pvalb        8.486837e-27  1.819699e-24 deeppink1
18 L2_3_IT_CTX  1.028593e-24  1.957736e-22 burlywood1
19 L5_PT_CTX    1.263471e-15  1.791418e-13 chocolate1
20 L4_5_IT_CTX  2.235783e-13  2.899976e-11 indianred2
21 L6_IT_CTX    8.146197e-04  4.641344e-02 orchid1
   Network
1  Bicor-None_signum0.24_minSize10_merge_ME_0.95_18409
2  Bicor-None_signum0.724_minSize10_merge_ME_0.95_18409
3  Bicor-None_signum0.9_minSize10_merge_ME_0.95_18409
4  Bicor-None_signum0.24_minSize8_merge_ME_0.95_18409
5  Bicor-None_signum0.9_minSize8_merge_ME_0.95_18409
6  Bicor-None_signum0.9_minSize8_merge_ME_0.95_18409
7  Bicor-None_signum0.724_minSize10_merge_ME_0.95_18409
8  Bicor-None_signum0.438_minSize10_merge_ME_0.95_18409
9  Bicor-None_signum0.24_minSize6_merge_ME_0.95_18409
10 Bicor-None_signum0.438_minSize6_merge_ME_0.95_18409
11 Bicor-None_signum0.438_minSize4_merge_ME_0.95_18409
12 Bicor-None_signum0.24_minSize10_merge_ME_0.95_18409
13 Bicor-None_signum0.3_minSize10_merge_ME_0.95_18409
14 Bicor-None_signum0.3_minSize10_merge_ME_0.95_18409
15 Bicor-None_signum0.35_minSize6_merge_ME_0.95_18409
16 Bicor-None_signum0.3_minSize6_merge_ME_0.95_18409
17 Bicor-None_signum0.266_minSize10_merge_ME_0.95_18409
18 Bicor-None_signum0.438_minSize4_merge_ME_0.95_18409
19 Bicor-None_signum0.3_minSize4_merge_ME_0.95_18409
20 Bicor-None_signum0.3_minSize8_merge_ME_0.95_18409
21 Bicor-None_signum0.3_minSize4_merge_ME_0.95_18409

In [32]:
write.csv(top_mods_df, file=paste0("data/enrichments/", network_dir, "_", set_source, "_enrichments.csv"), row.names=FALSE, quote=FALSE)